name: "fluke.algorithms.robust_fedavg.RobustFedAVG"

hyperparameters:
  model: "MNIST_2NN"
  server:
    weighted: true
  client:
    model: "MNIST_2NN"
    loss: CrossEntropyLoss
    local_epochs: 2
    batch_size: 32
    
    optimizer:
      lr: 0.01
      momentum: 0.9
      weight_decay: 0.0001
    
    scheduler:
      gamma: 1.0
      step_size: 1

    # --- Attack Configuration ---
    # The attack remains enabled. We are testing our algorithm's
    # performance *under* the same attack conditions.
    attack:
      enabled: true
      fraction: 0.3
      strength: 20.0